language: node_js

node_js:
  - "8"
  - "6"
  - "4"

env:
  - REDIS_VERSION=4.0.8
  - REDIS_VERSION=3.2.11
  - REDIS_VERSION=3.2.3
  - REDIS_VERSION=3.0.7

install:
  - npm install
  - test/setup-redis

before_script: test/start-redis
after_script: test/stop-redis
